name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-typecheck-test:
    name: Lint, Typecheck & Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma client
        run: npx prisma generate

      - name: Lint
        run: npm run lint

      - name: Type check
        run: npx tsc --noEmit

      - name: Unit tests
        run: npm run test

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: lint-typecheck-test

    env:
      NEXT_PUBLIC_SUPABASE_URL: https://placeholder.supabase.co
      NEXT_PUBLIC_SUPABASE_ANON_KEY: placeholder-anon-key
      DATABASE_URL: postgresql://placeholder:placeholder@localhost:5432/placeholder
      DIRECT_URL: postgresql://placeholder:placeholder@localhost:5432/placeholder

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Check bundle sizes
        run: |
          echo "=== Bundle Size Report ==="
          du -sh .next/static/chunks/*.js 2>/dev/null | sort -rh | head -20 || true
          echo ""
          echo "=== Total .next size ==="
          du -sh .next || true
